# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('elapsed_time', models.DecimalField(decimal_places=3, max_digits=65)),
            ],
        ),
    ]
