# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='elapsed_time',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
