# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170423_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='saved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
