# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_record_saved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
