# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-23 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170423_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='elapsed_time',
            field=models.FloatField(),
        ),
    ]
